name       : mozo
version    : 1.22.0
release    : 3
source     :
    - https://github.com/mate-desktop//mozo/archive/v1.22.0.tar.gz : 2a8b5239189ef82771905d148a010e9b3582b8009e523eb0bc8394401ce4af19
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Desktop menu editor
description: |
    Menu editor for MATE using the freedesktop.org menu specification.
builddeps  :
    - pkgconfig(libmate-menu)
    - pkgconfig(pygobject-3.0)
    - mate-common
rundeps    :
    - mate-menus
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
