name       : mozo
version    : 1.27.0
release    : 13
source     :
    - https://github.com/mate-desktop/mozo/releases/download/v1.27.0/mozo-1.27.0.tar.xz : 0d97e5dfb7c446bb552d563290927306ae4c6f2b385649e4161ece8776fdccc1
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Desktop menu editor
description: |
    Menu editor for MATE using the freedesktop.org menu specification.
builddeps  :
    - pkgconfig(libmate-menu)
    - pkgconfig(pygobject-3.0)
rundeps    :
    - mate-menus
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
