name       : mozo
version    : 1.26.1
release    : 11
source     :
    - https://github.com/mate-desktop/mozo/releases/download/v1.26.1/mozo-1.26.1.tar.xz : 0f24429a3b037bd0688ec4c391d9d8781e42b23ef345f5e50af1e72c5ef2fa39
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Desktop menu editor
description: |
    Menu editor for MATE using the freedesktop.org menu specification.
builddeps  :
    - pkgconfig(libmate-menu)
    - pkgconfig(pygobject-3.0)
rundeps    :
    - mate-menus
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
