name       : mozo
version    : 1.20.1
release    : 1
source     :
    - https://pub.mate-desktop.org/releases/1.20/mozo-1.20.1.tar.xz : 377b7fb55c66f3b57593cb800ba997d437f8c8b59a4d402953221634f0e2339b
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Desktop menu editor
description: |
    Menu editor for MATE using the freedesktop.org menu specification.
builddeps  :
    - pkgconfig(libmate-menu)
    - pkgconfig(pygobject-3.0)
rundeps    :
    - mate-menus
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
