name       : mozo
version    : 1.22.2
release    : 5
source     :
    - https://github.com/mate-desktop/mozo/archive/v1.22.2.tar.gz : bb2098d5d0adfdedd7141bc9748c045f7b90602ec7f9a99bae9912293a127873
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Desktop menu editor
description: |
    Menu editor for MATE using the freedesktop.org menu specification.
builddeps  :
    - pkgconfig(libmate-menu)
    - pkgconfig(pygobject-3.0)
    - mate-common
rundeps    :
    - mate-menus
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
