name       : mozo
version    : 1.24.0
release    : 7
source     :
    - https://github.com/mate-desktop/mozo/archive/v1.24.0.tar.gz : 3b3d09ab4970cfd3f9dfb5b755cfd361d750416a0a9cb33be35aa440668f3616
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Desktop menu editor
description: |
    Menu editor for MATE using the freedesktop.org menu specification.
builddeps  :
    - pkgconfig(libmate-menu)
    - pkgconfig(pygobject-3.0)
    - mate-common
rundeps    :
    - mate-menus
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
